[project]
name = "datasets"
version = "0.1.0"
description = "Add a short description here"
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.1,<3.13"
requests = ">=2.31.0,<2.32"
joblib = ">=1.4.2,<2"
matplotlib = ">=3.9.1,<4"
numpy = ">=2.1.1,<3"
pandas = ">=2.2.3,<3"
pyarrow = ">=17.0.0,<18"
altair = ">=5.4.1,<6"
marimo = ">=0.10.9,<0.11"

[pypi-dependencies]
playwright = ">=1.47.0, <2"
